# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./db.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
    db-data:
